# .github/workflows/lint.yml
name: Lint Next.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Run Next.js lint
        run: yarn lint